In [ ]:
# BD20 HW2

# Shishkin I.A.
# 135m

In [1]:
import numpy as np
import scipy.linalg
from functools import reduce

In [2]:
def Mean_cov_map(X):
    
    n = X.shape[1]  # number of vectors
    m = X.shape[0] # vectors dim
    
    S = np.sum(X, axis=1) # sum vector
    
    M  = [np.zeros(m) for i in range(m)] # cov matrix, default contains zeros
    
    for i in range(n):
        M += X[:, i].reshape(-1,1) @ X[:, i].reshape(1,-1)
    
    return n, S, M

In [3]:
def Mean_cov_reduce(x, y):
    return x[0]+y[0], x[1]+y[1], x[2]+y[2]

In [4]:
def Mean_cov_result(r):
    
    mean_vec = r[1] / r[0]
    
    cov_matrix =  r[2] - (r[1].reshape(-1,1) @ r[1].reshape(1,-1))/r[0]
    cov_matrix = cov_matrix / (r[0]-1)
    
    return mean_vec, cov_matrix

In [5]:
def Result(nodes):
    return Mean_cov_result(reduce(Mean_cov_reduce, map(Mean_cov_map, nodes)))

In [6]:
# example

m = 3   # Dimension - raws
n = 20  # Sample size - columns

X0 = np.array([[1.],[2.],[3.]])
V0 = np.array([[1., .5, .5],[.5, 1., .5],[.5, .5, 1.]])

Vs=scipy.linalg.sqrtm(V0)

X = X0 @ np.ones((1,n)) + Vs @ np.random.normal(size=(m,n))

nodes = [X[:,:5], X[:,5:10], X[:,10:15], X[:,15:20]]

In [7]:
# result for full data

Mean_cov_result(Mean_cov_map(X))

(array([1.17127003, 2.0798393 , 3.16566469]),
 array([[0.44299516, 0.39124832, 0.16839361],
        [0.39124832, 1.31863786, 0.71923647],
        [0.16839361, 0.71923647, 0.83516702]]))

In [8]:
# result for parts. It must be equal to full data result

Result(nodes)

(array([1.17127003, 2.0798393 , 3.16566469]),
 array([[0.44299516, 0.39124832, 0.16839361],
        [0.39124832, 1.31863786, 0.71923647],
        [0.16839361, 0.71923647, 0.83516702]]))

In [9]:
# verification for mean vector

np.mean(X, axis=1)

array([1.17127003, 2.0798393 , 3.16566469])

In [10]:
# verification for covariance matrix

np.cov(X)

array([[0.44299516, 0.39124832, 0.16839361],
       [0.39124832, 1.31863786, 0.71923647],
       [0.16839361, 0.71923647, 0.83516702]])